Repository Azure/ms-rest-browserauth, pull requests merged in 2018-11, with the labels that each got.

#8 Fix unit test script and linter violations
  package.json
  samples/react-app/src/registerServiceWorker.ts
Labels: in progress

#9 Rename package to "@azure/ms-rest-browserauth"
  lib/index.ts
  package-lock.json
  package.json
  rollup.config.js
Labels: in progress

#10 Remove Travis configuration and disable Node6 building
  .travis.yml
  azure-pipelines.yml
Labels: Unplanned-Sprint-126, in progress

#13 Improve sourcemaps to point at the original typescript source code
  .gitignore
  package-lock.json
  package.json
  rollup.config.js
Labels: Planned-Sprint-127, Started-Sprint-127, in progress

#16 Update package version
  package.json
Labels: in progress
